c3p0:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3307/lipstick?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  username: polaris_he
  password: 123456
  minPoolSize: 2
  maxPoolSize: 10
  initialPoolSize: 5
  maxIdleTime: 5000
  checkoutTimeout: 5000
  maxStatements: 20

spring:
  freemarker:
    charset: UTF-8
    cache: true
    allow-request-override: false
    expose-request-attributes: false
    expose-session-attributes: false
    content-type: text/html
    expose-spring-macro-helpers: false
    check-template-location: true
    suffix: .ftl
    template-loader-path: classpath:/templates
