CREATE TABLE brand (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(45) NOT NULL COMMENT 'code',
  name VARCHAR(45) NOT NULL COMMENT 'name',
  created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (id),
  UNIQUE INDEX udx_brand_code (code)
)ENGINE=InnoDB auto_increment=1 DEFAULT CHARSET=utf8mb4;
