CREATE TABLE brand (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(45) NOT NULL COMMENT 'code',
  name VARCHAR(45) NOT NULL COMMENT 'name',
  order tinyint NOT NULL COMMENT '顺序',
  created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (id),
  UNIQUE INDEX udx_brand_code (code)
)ENGINE=InnoDB auto_increment=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE category (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  code VARCHAR(45) NOT NULL COMMENT 'code',
  name VARCHAR(45) NOT NULL COMMENT 'name',
  order tinyint NOT NULL COMMENT '顺序',
  created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (id),
  UNIQUE INDEX udx_category_code (code)
)ENGINE=InnoDB auto_increment=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE brand_category_mapping (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  brand_code VARCHAR(45) NOT NULL COMMENT '品牌code',
  category_code VARCHAR(45) NOT NULL COMMENT '品类code',
  created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (id),
  UNIQUE INDEX idx_brand_category_mapping (brand_code,category_code)
)ENGINE=InnoDB auto_increment=1 DEFAULT CHARSET=utf8mb4;

CREATE TABLE lipstick (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  brand_id BIGINT NOT NULL COMMENT '品牌主键',
  category_id BIGINT NOT NULL COMMENT '品类主键',
  -- todo
  created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  PRIMARY KEY (id),
  KEY INDEX idx_brand_category_mapping (brand_id,category_id)
)ENGINE=InnoDB auto_increment=1 DEFAULT CHARSET=utf8mb4;